[metadata]
name = finchar
version = attr: finchar.__version__
author = Cian Ó Domhnaill
author_email = cian.odonnell@pulposemi.com
description = Finfet characterisation for gmid
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6
setup_requires = 
    numpy
    scipy
    matplotlib
    psf_utils
    tqdm
install_requires = 
    numpy
    scipy
    matplotlib
    psf_utils
    tqdm
    
[options.packages.find]
where = src
